defaults:
  - _self_
  - model: ???
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

seed: 42

hydra:
  output_subdir: null
  run:
    dir: ${output_dir:${name}}
  job:
    chdir: false
